services:
  ainara:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - ainara-network
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-community
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=secretpassword
    volumes:
      - mongo_data:/var/lib/mongodb
    restart: unless-stopped
    networks:
      - ainara-network

volumes:
  mongo_data:


networks:
  ainara-network:
    driver: bridge